version: '3'
services:
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: passwd
            MYSQL_DB: tohken_db
        volumes:
            - ./data:/var/lib/mysql
    web:
        build: .
        volumes:
            - ./app:/code
        ports:
            - "80:8000"
        depends_on:
            - db
        environment:
            WAIT_HOSTS: db:3306
    adminer:
        image: adminer
        ports:
            - 8081:8080
        depends_on:
            - db

