# Generated by Django 2.1.1 on 2019-03-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnance', models.CharField(max_length=100, null=True)),
                ('qcol1', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('qcol2', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('qcol3', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('qcol4', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('qcol5', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('qcol6', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('qcol7', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('qcol8', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('tcol1', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('tcol2', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('tcol3', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('tcol4', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('tcol5', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('tcol6', models.CharField(blank=True, choices=[('zone1', 'Zone 1')], max_length=100, null=True)),
                ('checkq_1', models.CharField(blank=True, choices=[('quenching', 'Quenching')], max_length=100, null=True)),
                ('checkt_2', models.CharField(blank=True, choices=[('quenching', 'Quenching')], max_length=100, null=True)),
                ('coveyor_length', models.FloatField(blank=True, null=True)),
                ('max_weight_value', models.FloatField(blank=True, null=True)),
                ('max_weight_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('furtype', models.CharField(blank=True, choices=[('trq', 'TRQ')], max_length=40, null=True)),
                ('furno', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PartMF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_no', models.IntegerField()),
                ('partcode', models.CharField(max_length=40, unique=True)),
                ('doc_code', models.CharField(blank=True, max_length=40, null=True)),
                ('treatcd', models.CharField(blank=True, max_length=40, null=True)),
                ('designno', models.CharField(blank=True, max_length=40, null=True)),
                ('partname', models.CharField(blank=True, max_length=80, null=True)),
                ('size', models.CharField(blank=True, max_length=60, null=True)),
                ('mat', models.CharField(max_length=60, null=True)),
                ('shtester1', models.CharField(blank=True, max_length=20, null=True)),
                ('low1', models.FloatField(blank=True, null=True)),
                ('up1', models.FloatField(blank=True, null=True)),
                ('shtester2', models.CharField(blank=True, max_length=20, null=True)),
                ('low2', models.FloatField(blank=True, null=True)),
                ('up2', models.FloatField(blank=True, null=True)),
                ('shtester3', models.CharField(blank=True, max_length=20, null=True)),
                ('low3', models.FloatField(blank=True, null=True)),
                ('up3', models.FloatField(blank=True, null=True)),
                ('chtester1', models.CharField(blank=True, max_length=20, null=True)),
                ('chlow1', models.FloatField(blank=True, null=True)),
                ('chup1', models.FloatField(blank=True, null=True)),
                ('chtester2', models.CharField(blank=True, max_length=20, null=True)),
                ('chlow2', models.FloatField(blank=True, null=True)),
                ('chup2', models.FloatField(blank=True, null=True)),
                ('othertester', models.CharField(blank=True, max_length=20, null=True)),
                ('olow1', models.FloatField(blank=True, null=True)),
                ('oup1', models.FloatField(blank=True, null=True)),
                ('effpoint1', models.CharField(blank=True, max_length=20, null=True)),
                ('effcriterion1', models.IntegerField(blank=True, null=True)),
                ('eff_low1', models.FloatField(blank=True, null=True)),
                ('eff_up1', models.FloatField(blank=True, null=True)),
                ('effpoint2', models.CharField(blank=True, max_length=20, null=True)),
                ('effcriterion2', models.IntegerField(blank=True, null=True)),
                ('eff_low2', models.FloatField(blank=True, null=True)),
                ('eff_up2', models.FloatField(blank=True, null=True)),
                ('total_measures', models.IntegerField(blank=True, null=True)),
                ('rev_date', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('del_flag', models.IntegerField(blank=True, null=True)),
                ('qo_no', models.CharField(max_length=40)),
            ],
        ),
    ]
