# Generated by Django 2.1.1 on 2019-03-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmf',
            name='kgperpc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
