# Generated by Django 2.1.1 on 2019-03-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_partmf_kgperpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantMF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.IntegerField(null=True)),
                ('data_code', models.CharField(max_length=10)),
                ('data1', models.CharField(blank=True, max_length=50, null=True)),
                ('data2', models.CharField(blank=True, max_length=50, null=True)),
                ('data3', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
