# Generated by Django 2.1.1 on 2019-03-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_constantmf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantmf',
            name='data1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='constantmf',
            name='data2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='constantmf',
            name='data3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='constantmf',
            name='data_code',
            field=models.CharField(max_length=20),
        ),
    ]
