# Generated by Django 2.1.1 on 2019-03-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20190330_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnance',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
