# Generated by Django 2.1.1 on 2019-04-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_furnance_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnance',
            name='enable_cols',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
