# Generated by Django 2.1.1 on 2019-04-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_furnance_enable_cols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnance',
            name='enable_cols',
        ),
        migrations.AddField(
            model_name='furnance',
            name='enable_qcols',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='furnance',
            name='enable_tcols',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
