# Generated by Django 2.1.1 on 2019-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_partphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnance',
            name='furtype',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
