# Generated by Django 2.1.1 on 2019-03-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartMF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custno', models.IntegerField()),
                ('partcode', models.CharField(blank=True, max_length=40, null=True)),
                ('documentcode', models.CharField(blank=True, max_length=40, null=True)),
                ('treatcode', models.CharField(blank=True, max_length=100, null=True)),
                ('designno', models.CharField(blank=True, max_length=100, null=True)),
                ('partname', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('shtester1', models.CharField(blank=True, max_length=100, null=True)),
                ('sh1low', models.FloatField(blank=True, null=True)),
                ('sh1up', models.FloatField(blank=True, null=True)),
                ('shtester2', models.CharField(blank=True, max_length=100, null=True)),
                ('sh2low', models.FloatField(blank=True, null=True)),
                ('sh2up', models.FloatField(blank=True, null=True)),
                ('shtester3', models.CharField(blank=True, max_length=100, null=True)),
                ('sh3low', models.FloatField(blank=True, null=True)),
                ('sh3up', models.FloatField(blank=True, null=True)),
                ('chtester1', models.CharField(blank=True, max_length=100, null=True)),
                ('ch1low', models.FloatField(blank=True, null=True)),
                ('ch1up', models.FloatField(blank=True, null=True)),
                ('chtester2', models.CharField(blank=True, max_length=100, null=True)),
                ('ch2low', models.FloatField(blank=True, null=True)),
                ('ch2up', models.FloatField(blank=True, null=True)),
                ('othertester', models.CharField(blank=True, max_length=100, null=True)),
                ('olow', models.FloatField(blank=True, null=True)),
                ('oup', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
