# Generated by Django 2.1.1 on 2019-03-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.PartMF', to_field='partcode')),
            ],
        ),
    ]
