# Generated by Django 2.1.1 on 2019-03-19 17:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='safety',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('safe1', 'Safe1'), ('safe2', 'Safe2')], max_length=11, null=True),
        ),
    ]
