# Generated by Django 2.1.1 on 2019-03-22 05:44

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20190320_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfurnance',
            name='body',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
