# Generated by Django 2.1.1 on 2019-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20190322_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfurnance',
            name='checkq_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='checkt_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='coveyor_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='furno',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='furtype',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='max_weight_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='max_weight_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='qcol8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='tcol1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='tcol2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='tcol3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='tcol4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='tcol5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='tcol6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
