# Generated by Django 2.1.1 on 2019-03-23 03:01

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20190322_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfurnance',
            name='values',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
