# Generated by Django 2.1.1 on 2019-03-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobfurnance_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(default='', max_length=40)),
                ('colName', models.CharField(default='', max_length=40, null=True)),
                ('fvalue', models.FloatField(blank=True, null=True)),
                ('tvalue', models.CharField(blank=True, max_length=200, null=True)),
                ('jobfurnance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobFurnance')),
            ],
        ),
    ]
