# Generated by Django 2.1.1 on 2019-03-30 13:32

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfurnance',
            name='keys',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
