# Generated by Django 2.1.1 on 2019-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_jobphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
