# Generated by Django 2.1.1 on 2019-04-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_jobphoto_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPhotoInspectQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='jobphotos/')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job')),
            ],
        ),
    ]
