# Generated by Django 2.1.1 on 2019-04-04 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_jobphotoinspectq'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('trial', 'Trial'), ('standard', 'Standard')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='main_furnance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Furnance'),
        ),
    ]
