# Generated by Django 2.1.1 on 2019-04-04 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20190404_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='version_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
