# Generated by Django 2.1.1 on 2019-04-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20190404_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='version_code',
            field=models.CharField(default='XXX', max_length=100),
        ),
    ]
