# Generated by Django 2.1.1 on 2019-04-04 04:52

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20190404_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='meta_data',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
