# Generated by Django 2.1.1 on 2019-04-04 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20190404_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 4, 4, 5, 44, 51, 822013)),
            preserve_default=False,
        ),
    ]
