# Generated by Django 2.1.1 on 2019-04-12 05:55

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_jobinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfurnance',
            name='batch_values',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
        migrations.AddField(
            model_name='jobfurnance',
            name='is_batch',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
