# Generated by Django 2.1.1 on 2019-04-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_settingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingphoto',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobSetting'),
        ),
    ]
