# Generated by Django 2.1.1 on 2019-04-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_furnance_tparams'),
        ('job', '0027_settingphoto_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShotBlast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ptn_no', models.IntegerField(null=True)),
                ('time_op', models.FloatField(null=True)),
                ('kg_time', models.FloatField(null=True)),
                ('furnance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Furnance')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job')),
            ],
        ),
        migrations.AddField(
            model_name='sbphoto',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.ShotBlast'),
        ),
    ]
