# Generated by Django 2.1.1 on 2019-04-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_auto_20190417_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbphoto',
            old_name='setting',
            new_name='sb',
        ),
    ]
