# Generated by Django 2.1.1 on 2019-04-18 05:45

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_auto_20190417_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotblast',
            name='values',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
