# Generated by Django 2.1.1 on 2019-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_jobexportdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexportdata',
            name='revision_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
