# Generated by Django 2.1.1 on 2019-04-29 07:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_jobexportdata_revision_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='safety',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('helmet', 'หมวกพนักงาน'), ('safety_shoes', 'รองเท้า Safety'), ('glass', 'แว่นตา'), ('ear_cover', 'ที่ครอบหู'), ('ear_fill', 'ที่อุดหู'), ('belt', 'เข็มขัดนิรภัย'), ('nose', 'ผ้าปิดจมูก'), ('glove', 'ถุงมือยาง'), ('eam', 'เอี้ยม'), ('glove_c', 'ถุงมือผ้า'), ('arm', 'ปลอกแขนทางความร้อน'), ('back', 'แผ่นรองหลัง'), ('other', 'อื่นๆ')], max_length=300, null=True, verbose_name='Safety Protective'),
        ),
    ]
