# Generated by Django 2.1.1 on 2019-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_jobexportdata_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfurnance',
            name='template_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
