# Generated by Django 2.1.1 on 2019-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_jobfurnance_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobphoto',
            name='photo',
            field=models.ImageField(upload_to='jobphotos/'),
        ),
        migrations.AlterField(
            model_name='jobphotoinspectq',
            name='photo',
            field=models.ImageField(upload_to='jobphotos/'),
        ),
    ]
