# Generated by Django 2.1.1 on 2019-05-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_auto_20190506_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job')),
            ],
        ),
    ]
