# Generated by Django 2.1.1 on 2019-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_inspectionphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfurnance',
            name='enable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
