# Generated by Django 2.1.1 on 2019-05-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_jobfurnancefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobfurnancefile',
            old_name='jf',
            new_name='jobFurnance',
        ),
    ]
