# Generated by Django 2.1.1 on 2019-06-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0040_auto_20190518_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinspection',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
