# Generated by Django 2.1.1 on 2019-06-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0041_auto_20190622_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinspection',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='jobinspection',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='jobinspection',
            name='file3',
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
