# Generated by Django 2.1.1 on 2019-06-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0042_auto_20190622_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='version_code',
        ),
    ]
