# Generated by Django 2.1.1 on 2019-06-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0043_remove_job_version_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='version_code',
            field=models.IntegerField(default=1),
        ),
    ]
