# Generated by Django 2.1.1 on 2019-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0044_job_version_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rev_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
