# Generated by Django 2.1.1 on 2019-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0045_job_rev_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rev_note',
            field=models.TextField(blank=True, null=True, verbose_name='Revision note'),
        ),
    ]
