# Generated by Django 2.1.1 on 2019-11-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0046_auto_20190912_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='c_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('trial', 'Trial'), ('trial_approve', 'Trial Approved'), ('standard', 'Standard')], default='draft', max_length=40),
        ),
    ]
