# Generated by Django 2.1.1 on 2020-10-05 03:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0047_auto_20191117_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='meta_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobfurnance',
            name='batch_values',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobfurnance',
            name='body',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobfurnance',
            name='keys',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobfurnance',
            name='values',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tester',
            field=models.CharField(choices=[('MHv10g.', 'MHv10g.'), ('MHv25g.', 'MHv25g.'), ('MHv50g.', 'MHv50g.'), ('MHv100g.', 'MHv100g.'), ('MHv200g.', 'MHv200g.'), ('MHv300g.', 'MHv300g.'), ('MHv500g.', 'MHv500g.'), ('MHv1Kg.', 'MHv1Kg.'), ('Hv5Kg.', 'Hv5Kg.'), ('Hv10Kg.', 'Hv10Kg.'), ('Hv20Kg.', 'Hv20Kg.'), ('Hv30Kg.', 'Hv30Kg.'), ('Hv50Kg.', 'Hv50Kg.'), ('HR15N', 'HR15N'), ('HR30N', 'HR30N'), ('HRA', 'HRA'), ('HRB', 'HRB'), ('HRC', 'HRC'), ('HS', 'HS'), ('HB', 'HB'), ('Micro scope (x50)', 'Micro scope (x50)'), ('Micro scope (x100)', 'Micro scope (x100)'), ('Micro scope (x400)', 'Micro scope (x400)'), ('Micro scope (x100,x400)', 'Micro scope (x100,x400)'), ('Micro scope (x500)', 'Micro scope (x500)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobsetting',
            name='values',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shotblast',
            name='values',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
