# Generated by Django 2.1.1 on 2021-03-09 03:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0050_job_safety_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='part_rank',
            field=models.TextField(blank=True, null=True, verbose_name='Part Rank'),
        ),
        migrations.AlterField(
            model_name='job',
            name='safety_inspection',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('helmet', 'หมวกพนักงาน'), ('safety_shoes', 'รองเท้า Safety'), ('glass', 'แว่นตา'), ('ear_cover', 'ที่ครอบหู'), ('ear_fill', 'ที่อุดหู'), ('belt', 'เข็มขัดนิรภัย'), ('nose', 'ผ้าปิดจมูก'), ('glove', 'ถุงมือยาง'), ('eam', 'เอี้ยม'), ('glove_c', 'ถุงมือผ้า'), ('arm', 'ปลอกแขนทางความร้อน'), ('back', 'แผ่นรองหลัง'), ('other', 'อื่นๆ')], default='helmet,safety_shoes,nose,glove,glove_c', max_length=500, null=True, verbose_name='Safety Inspection'),
        ),
    ]
