INSP_ITEMS = (
    ('surface-hardness', 'Surface Hardness'),
    ('core-hardness', 'Core Hardness'),
    ('internal-hardness', 'Internal Hardness'),
    ('eff-e550', 'Effective Case-Depth E(550)'),
    ('eff-e465', 'Effective Case-Depth E(465)'),
    ('eff-e450', 'Effective Case-Depth E(450)'),
    ('eff-e400', 'Effective Case-Depth E(400)'),
    ('eff-e350', 'Effective Case-Depth E(350)'),
    ('eff-e513', 'Effective Case-Depth E(513)'),
    ('eff-e363', 'Effective Case-Depth E(363)'),
    ('eff-e420', 'Effective Case-Depth E(420)'),
    ('eff-e300', 'Effective Case-Depth E(300)'),
    ('eff-e390', 'Effective Case-Depth E(390)'),
    ('eff-e580', 'Effective Case-Depth E(580)'),
    ('eff-e440', 'Effective Case-Depth E(440)'),
    ('eff-e600', 'Effective Case-Depth E(600)'),
    ('eff-e360', 'Effective Case-Depth E(360)'),
    ('eff-e500', 'Effective Case-Depth E(500)'),
    ('eff-e593', 'Effective Case-Depth E(593)'),
    ('eff-e700', 'Effective Case-Depth E(700)'),
    ('eff-e392', 'Effective Case-Depth E(392)'),
    ('eff-e446', 'Effective Case-Depth E(446)'),
    ('eff-e530', 'Effective Case-Depth E(530)'),
    ('total-case-depth', 'Total case depth'),
    ('micro', 'Micro-structure')
)
