from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.JobListView.as_view(), name='job-index'),
    url(r'^part-autocomplete/$',views.PartAutocomplete.as_view(),name='part-autocomplete',),
    path('loadjobfurnance/<int:pk>', views.loadjobfurnance, name='loadjobfurnance'),
    path('job_add_jf/<int:pk>', views.job_add_jf, name='job-add-jf'),
    path('job_api/get/<int:pk>', views.job_api, name='job-get'),
    path('export/<int:pk>', views.export_api, name='export-api' ),
    path('jobsetting_api/get/<int:pk>', views.jobsetting_api, name='job-setting-get'),
    path('sb_api/get/<int:pk>', views.sb_api, name='sb-api'),
    path('jf_api/get/<int:pk>', views.jobfurnance_api, name='jf-api'),
    path('job_api/createsetting/<int:pk>', views.job_createsetting, name='job-create-setting'),
    path('job_api/sb/new/<int:pk>', views.createSb, name='sb-create'),
    path('job_api/sb/<int:pk>', views.list_sb, name='sb-list'),
    path('job_api/delete_setting', views.job_delete_setting, name='job-delete-setting'),
    path('sb/delete', views.sb_delete, name='sb-delete'),
    path('setting_photo/new', views.create_sb_photo, name='create-sb-photo'),
    path('jf_photo/new', views.upload_file, name='jobfurnance-upload-file'),
    path('photo_api', views.photo_api, name='photo-api'),
    path('sb/photo/new', views.create_setting_photo, name='create-setting-photo'),
    path('sb/photo/delete', views.delete_setting_photo, name='delete-setting-photo'),
    path('setting_photo/', views.get_setting_photo, name='get-setting-photo'),
    path('sb_photo/', views.get_sb_photo, name='get-sb-photo'),
    path('setting_photo/upload', views.update_setting_photo, name='update-setting-photo'),
    path('sb_photo/upload', views.upload_sb_photo, name='upload-sb-photo'),
    path('setting_photo/edit', views.update_setting_photo_data, name='edit-setting-photo-data'),
    path('sb_photo/edit', views.update_sbphoto_data, name='update-sbphoto-data'),
    path('sb_photo/delete', views.delete_sb_photo, name='delete-sbphoto'),
    path('jobs/', views.JobListView.as_view(), name = 'job-list'),
    path('jobs/prepare', views.TrialView.as_view(), name = 'job-prepare'),
    path('jobs/test', views.jobpost, name = 'job-post'),
    path('jobs/create', views.TrialJobNew.as_view(), name = 'job-new'),
    path('jobs/new', views.JobCreateView.as_view(), name = 'job-create'),
    #path('jobs/edit/<int:pk>', views.JobEditView.as_view(), name = 'job-edit'),
    path('jobs/edit/<int:pk>', views.jobedit, name  = 'job-edit'),
    path('furnance_list/', views.furnance_list, name  = 'furnance-list-api'),
    path('jobs/revision/<int:pk>', views.job_revision, name  = 'job-revision'),
    path('jobs/delete/<int:pk>', views.JobDeleteView.as_view(), name = 'job-delete'),
    path('jobfurnances/new', views.JobFurnanceCreateView.as_view(), name = 'jobfurnance-create'),
        ]
